### ISSUE TITLE
[bug] Erro ao pesquisar produto

### ISSUE THREAD

**Issue by gugacavalieri** [thiagormagalhaes/search-deals-playstation-telegram-bot#11]
## Expected Behavior
O Bot deveria retornar as informações do produto

## Current Behavior
Nada ocorre.
![image](https://user-images.githubusercontent.com/4624484/46617195-8958e180-caf2-11e8-9210-fc441750c97c.png)

Uma exceção é lançada no método `product`
![image](https://user-images.githubusercontent.com/4624484/46617236-a097cf00-caf2-11e8-8a1a-fa761463e631.png)

## Steps to Reproduce

1. Rodar o bot com `python3 bot.py` 
2. Utilizar o comando `/product UP0006-CUSA11600_00-FIFAFOOTBALL2019`

## Additional Info

* O erro ocorre para produtos que não estão em promoção na PSN Store BR

**Comment by gugacavalieri** [comment]
Vou trabalhar neste issue :smile:

**Comment by gugacavalieri** [comment]
Posso trabalhar neste issue :)

**Comment by thiagormagalhaes** [comment]
De certa forma não é um erro, pois coloquei para fazer a busca só nas promoções da PSN Store BR. Mas seria uma boa:

*  Fazer um tratamento quando o produto não for encontrado.
*  Ter a opção de pesquisar todos os produtos da PSN Store BR
