### ISSUE TITLE
Refatorar código

### ISSUE THREAD

**Issue by thiagormagalhaes** [thiagormagalhaes/search-deals-playstation-telegram-bot#15]
https://codeclimate.com/github/thiagormagalhaes/search-deals-playstation-telegram-bot/issues?category=duplication&engine_name%5B%5D=structure&engine_name%5B%5D=duplication

**Comment by philippeoz** [comment]
Olá @thiagormagalhaes posso pegar esta issue?
Pensei em algumas refatorações, aplicar pep8, adicionar decouple e um exemplo de arquivo de configurações.

**Comment by thiagormagalhaes** [comment]
Fique a vontade :D

**Comment by SamuelsSantos** [comment]
@philippeoz como estava montando os testes,adicionei o decouple. Depois podemos trocar uma ideia a respeito.

**Comment by SamuelsSantos** [comment]
@philippeoz  amanhã vou para OktoberFest, vou fazer o commit no meu fork pra você ver o que eu já tinha feito. Trocamos uma ideia sábado se eu não tiver de ressaca. abs
