### ISSUE TITLE
Add a CONTRIBUTING.md 

### ISSUE THREAD

**Issue by SamuelsSantos** [thiagormagalhaes/search-deals-playstation-telegram-bot#18]
Add a CONTRIBUTING.md file with contribution guidelines to your repo. #

**Comment by SamuelsSantos** [comment]
add Label HacktoberFest conforme link da competição

https://hacktoberfest.digitalocean.com/#gettingstarted

**Comment by thiagormagalhaes** [comment]
Obrigado pela contribuição @SamuelsSantos
