### ISSUE TITLE
CodeCoverage Badge

### ISSUE THREAD

**Issue by SamuelsSantos** [thiagormagalhaes/search-deals-playstation-telegram-bot#22]
- [x] Configurar o projeto https://codecov.io/gh
- [x] Incluir badge no Readme.

@thiagormagalhaes favor criar uma conta em https://codecov.io/gh
para adicionar o badge da cobertura de código

**Comment by SamuelsSantos** [comment]
Já estou implementando. Adiciona a label #hacktoberfest
Abs

**Comment by SamuelsSantos** [comment]
@thiagormagalhaes já terminei esta issue, mas para ela rodar tudo certo na sua branch precisamos fazer alguns ajustes no seu setup do Travis e do Codacy. Aguardo contato.

**Comment by thiagormagalhaes** [comment]
@SamuelsSantos me add para a gente trocar umas idéias. Meu número: 85 99169-4100

**Comment by thiagormagalhaes** [comment]
Deu certo, @SamuelsSantos .

**Comment by SamuelsSantos** [comment]
Show!!!

Github estava instável mesmo.
