### ISSUE TITLE
Ajuste nas Métricas CI

### ISSUE THREAD

**Issue by SamuelsSantos** [thiagormagalhaes/search-deals-playstation-telegram-bot#23]
Remover métricas do CI para arquivos markdown e de Tests.

<img width="1016" alt="screen shot 2018-10-17 at 01 48 38" src="https://user-images.githubusercontent.com/5309960/47062861-def65380-d1ae-11e8-80b9-782b7a65d960.png">

**Comment by thiagormagalhaes** [comment]
Feito. Obrigado pela sugestão @SamuelsSantos .

**Comment by thiagormagalhaes** [comment]
Feito. Obrigado pela sugestão @SamuelsSantos .
