### ISSUE TITLE
Adicionar testes básicos

### ISSUE THREAD

**Issue by thiagormagalhaes** [thiagormagalhaes/search-deals-playstation-telegram-bot#3]

**Comment by SamuelsSantos** [comment]
@thiagormagalhaes vou pegar esta issue.

**Comment by thiagormagalhaes** [comment]
@SamuelsSantos ainda irá trabalhar nesta issue?

**Comment by SamuelsSantos** [comment]
@thiagormagalhaes ainda estou trabalhando nela sim. Estou realizando alguns ajustes no código, por causa dos testes.
